all:
  vars:
    ansible_connection: ssh
    ansible_user: root
    ansible_become: true
    ansible_ssh_private_key_file: ~/.ssh/id_rsa
    ansible_ssh_common_args: -o StrictHostKeyChecking=no

zookeeper:
  hosts:
    128.199.158.242:

kafka_broker:
  hosts:
    128.199.158.242:
    128.199.134.34:
    128.199.158.217:

schema_registry:
  hosts:
    188.166.176.166:

ksql:
  hosts:
    188.166.176.166:

kafka_connect:
  hosts:
    188.166.176.166:
      vars:
        kafka_connect_confluent_hub_plugins:
          - confluentinc/kafka-connect-datagen:0.4.0

control_center:
  hosts:
    206.189.87.111:
